"""Build the two datasets from the public Periods file.

census(max_loop=9): every completed primitive phi^4 graph with 3 <= L <= max_loop
    (299 graphs through 9 loops). Non-products are read from Periods; products (graphs
    with a 3-vertex cut, which Periods omits) are regenerated by gluing along triangles.
    Label: weight_drop = 1 iff c2 = 0. For non-products this is the Periods annotation;
    for products it is a theorem (products have c2 = 0, and their periods are products of
    lower-loop periods, so the weight drops).

irreducible(loops): every irreducible ("prime ancestor") form at the given loop orders:
    graphs admitting no double-triangle reduction and no product split, K5 excluded.
"""
from collections import defaultdict

from . import graphs, periods
from .features import features


def census(periods_path, max_loop=9):
    E = periods.parse(periods_path)
    by_loop, recs = defaultdict(list), {}
    for (l, m), f in sorted(E.items()):
        if 3 <= l <= max_loop:
            G = periods.to_graph(f[0])
            k = graphs.canon(G)
            assert k not in recs, f"duplicate graph P[{l},{m}]"
            by_loop[l].append(G)
            recs[k] = dict(source=f"P[{l},{m}]", c2=f[4], weight_drop=periods.c2_label(f[4]))
    for L in range(5, max_loop + 1):
        for k, H in graphs.all_products(by_loop, L).items():
            assert k not in recs and graphs.is_primitive(H)
            by_loop[L].append(H)
            recs[k] = dict(source="product", c2="0 (product)", weight_drop=1)
    rows = []
    for k, r in recs.items():
        G = graphs.canon_graph(k)
        anc = graphs.ancestor(G)
        atype = graphs.ancestor_type(anc)
        row = dict(g6=graphs.canon_g6(k), **r, ancestor_type=atype,
                   family=graphs.canon_g6(anc[0]) if atype == "prime" else "")
        row.update(features(G))
        rows.append(row)
    rows.sort(key=lambda r: (r["L"], r["g6"]))
    return rows


def irreducible(periods_path, loops=range(6, 11)):
    E = periods.parse(periods_path)
    rows, seen = [], set()
    for (l, m), f in sorted(E.items()):
        if l not in loops:
            continue
        G = periods.to_graph(f[0])
        if graphs.dt_moves(G) or graphs.split_moves(G):
            continue
        k = graphs.canon(G)
        lab = periods.c2_label(f[4])
        if k in seen or lab is None:
            continue
        seen.add(k)
        row = dict(g6=graphs.canon_g6(k), source=f"P[{l},{m}]", c2=f[4], weight_drop=lab)
        row.update(features(G))
        rows.append(row)
    rows.sort(key=lambda r: (r["L"], r["g6"]))
    return rows
