"""Run the audit, stage by stage. Reads data/built/*.csv (see build_data.py), writes
results/results.json, results/SUMMARY.md and figures/auc_staircase.png."""
import csv
import json
import os
import sys
from collections import Counter

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from phi4audit.cv import evaluate, hgb  # noqa: E402
from phi4audit.features import FEATURE_KEYS  # noqa: E402

DATA = "data/built"
census = list(csv.DictReader(open(f"{DATA}/census_L3-9.csv")))
irred = list(csv.DictReader(open(f"{DATA}/irreducible_L6-10.csv")))


def Xy(rows, keys=FEATURE_KEYS):
    return (np.array([[float(r[k]) for k in keys] for r in rows]),
            np.array([int(r["weight_drop"]) for r in rows]))


def stage(name, desc, rows, keys=FEATURE_KEYS, grouped=False):
    X, y = Xy(rows, keys)
    groups = np.array([r["family"] for r in rows]) if grouped else None
    res = dict(stage=name, description=desc, n=len(y), positives=int(y.sum()), **evaluate(X, y, groups))
    if grouped:
        res["positive_families"] = len(set(groups[y == 1]))
        res["families"] = len(set(groups))
    g, l = res["gbt"], res["logistic"]
    print(f"[{name}] n={len(y)} pos={int(y.sum())}  GBT {g['mean']:.3f}±{g['std']:.3f}  "
          f"logistic {l['mean']:.3f}±{l['std']:.3f}  shuffled {res['shuffled_labels']}"
          + (f"  unscorable folds {l['folds_unscorable']}/{l['folds_total']}" if grouped else ""))
    return res


R = {}

# Stage 1 -- the headline: does the label show up in elementary graph invariants?
R["1"] = stage("1 baseline", "all 299 graphs, 24 features, random folds", census)
X, y = Xy(census)
from sklearn.inspection import permutation_importance  # noqa: E402
pi = permutation_importance(hgb().fit(X, y), X, y, n_repeats=10, random_state=0, scoring="roc_auc")
R["1"]["importance_top5"] = [(k, round(float(v), 3)) for k, v in
                             sorted(zip(FEATURE_KEYS, pi.importances_mean), key=lambda t: -t[1])[:5]]
print("    permutation importance:", R["1"]["importance_top5"])

# Stage 2 -- the top feature restates a theorem: a 3-vertex cut makes G a product, and
# products have c2 = 0. Check it is deterministic, then remove it two ways.
ct = Counter((r["vertex_conn"], r["weight_drop"]) for r in census)
R["vertex_conn_x_label"] = {f"vertex_conn={v}": {"c2!=0": ct[(v, '0')], "c2=0": ct[(v, '1')]}
                            for v in sorted({r["vertex_conn"] for r in census})}
print("    vertex_conn x label:", R["vertex_conn_x_label"])
R["2a"] = stage("2a no products", "vertex_conn = 4 only (the 50 products removed)",
                [r for r in census if r["vertex_conn"] == "4"])
R["2b"] = stage("2b no connectivity", "all 299, vertex_conn and edge_conn dropped", census,
                [k for k in FEATURE_KEYS if k not in ("vertex_conn", "edge_conn")])

# Stage 3 -- products hide: 57 of the 72 remaining positives reduce to a product after
# double-triangle reductions (c2 is invariant under them). Keep prime ancestors only.
prime = [r for r in census if r["ancestor_type"] == "prime"]
R["3"] = stage("3 prime ancestors", "graphs whose ancestor is a single non-K5 graph", prime)

# Stage 4 -- families leak: the 15 positives come from only 4 ancestor families and the
# label is constant on a family. Hold out whole families.
R["4"] = stage("4 families held out", "prime ancestors, grouped by ancestor family", prime, grouped=True)

# Stage 5 -- the ceiling: every irreducible form through 10 loops, one row per family.
R["5"] = stage("5 all families to L=10", "all irreducible forms L=6..10 (each its own family)", irred)
X, y = Xy(irred)
med = {k: (float(np.median(X[y == 1, i])), float(np.median(X[y == 0, i])))
       for i, k in enumerate(FEATURE_KEYS) if k in ("aut", "n_distinct_ev", "triangles", "girth")}
R["5"]["medians_c2zero_vs_rest"] = med
print("    medians (c2=0 vs rest):", med)

os.makedirs("results", exist_ok=True)
json.dump(R, open("results/results.json", "w"), indent=1)

# ---------------------------------------------------------------- summary + figure
ORDER = ["1", "2a", "2b", "3", "4"]
lines = ["# Results (generated by `make reproduce`)", "",
         "ROC AUC, 5-fold CV repeated 20x, mean ± std over repeats. Shuffled-label control in the last column.", "",
         "| stage | data | n (c2=0) | gradient boosting | logistic | shuffled labels (GBT / logistic) |",
         "|---|---|---|---|---|---|"]
for k in ORDER + ["5"]:
    r = R[k]
    lines.append(f"| {r['stage']} | {r['description']} | {r['n']} ({r['positives']}) | "
                 f"{r['gbt']['mean']:.3f} ± {r['gbt']['std']:.3f} | {r['logistic']['mean']:.3f} ± {r['logistic']['std']:.3f} | "
                 f"{r['shuffled_labels']['gbt']:.2f} / {r['shuffled_labels']['logistic']:.2f} |")
lines += ["", f"Stage 1 permutation importance (GBT): {R['1']['importance_top5']}",
          f"vertex connectivity × label: {R['vertex_conn_x_label']}",
          f"Stage 4: {R['4']['families']} families, {R['4']['positive_families']} with c2 = 0; "
          f"{R['4']['logistic']['folds_unscorable']}/{R['4']['logistic']['folds_total']} test folds had no positive family and were not scored.",
          f"Stage 5 medians (c2 = 0 vs rest): {R['5']['medians_c2zero_vs_rest']}"]
open("results/SUMMARY.md", "w").write("\n".join(lines) + "\n")

import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
STAGES = ["1", "2b", "3", "4"]
labels = ["1. all 299 graphs", "2. connectivity\nfeatures dropped", "3. prime\nancestors only", "4. whole families\nheld out"]
fig, ax = plt.subplots(figsize=(7.2, 4.0))
w = 0.36
for j, (model, colour, name) in enumerate([("gbt", "#2a78d6", "gradient boosting"),
                                          ("logistic", "#eb6834", "logistic regression")]):
    xs = np.arange(4) + (j - 0.5) * w
    m = [R[k][model]["mean"] for k in STAGES]
    e = [R[k][model]["std"] for k in STAGES]
    ax.bar(xs, m, width=w - 0.03, color=colour, label=name, zorder=2)
    ax.errorbar(xs, m, yerr=e, fmt="none", ecolor="#444444", elinewidth=1, capsize=3, zorder=3)
    for x, v, err in zip(xs, m, e):
        ax.text(x, v + err + 0.012, f"{v:.2f}", ha="center", fontsize=8, color="#222222")
ax.axhline(0.5, ls="--", color="#888888", lw=1, zorder=1)
ax.text(3.62, 0.507, "chance", fontsize=8, color="#666666", ha="right")
ax.set_xticks(range(4), labels, fontsize=8.5)
ax.set_ylim(0.4, 1.0)
ax.set_ylabel("cross-validated ROC AUC")
ax.grid(axis="y", color="#e6e6e6", zorder=0)
for side in ("top", "right"):
    ax.spines[side].set_visible(False)
ax.legend(frameon=False, fontsize=8.5, loc="upper right")
ax.set_title("Predicting c2 = 0 from 24 graph invariants, one leak removed per stage", fontsize=10)
fig.tight_layout()
os.makedirs("figures", exist_ok=True)
fig.savefig("figures/auc_staircase.png", dpi=200)
print("wrote results/results.json, results/SUMMARY.md, figures/auc_staircase.png")
